---
- name: Installing necessary packages to allow apt to use a repository over HTTPS
  apt:
    update_cache: true
    cache_valid_time: "3600"
    state: present
    name:
      - apt-transport-https
      - ca-certificates